### ISSUE TITLE
iso3c column aren't iso3c codes

### ISSUE THREAD

**Issue by thereseanders** [andybega/states#19]
The `iso3c` column aren not [ISO 3166-1 alpha-3 codes](https://unstats.un.org/unsd/tradekb/knowledgebase/country-code) based on the UN Statistics division. Naming them `iso3c` is misleading.

I believe these are custom 3-letter country codes in the Gleditsch & Ward data that I am guessing are based on COW 3-letter country codes (with a few exceptions). 

The [countrycode](https://cran.r-project.org/web/packages/countrycode/countrycode.pdf) package has all three codes to verify these aren't iso3c codes:
```r 
library(countrycode)
countrycode::codelist %>%
  dplyr::select(country.name.en, cowc, gwc, gwn, iso3c)
```

**Comment by andybega** [comment]
Hi, thanks! I have renamed the columns `gwn` and `cowc`, what do you think?

**Comment by thereseanders** [comment]
Yes, that clarifies it!
